version: '3'
services:
        web:
                image: neptune_2025
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8204:8204"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
